### ISSUE TITLE
Can't search for channels or add by name

### ISSUE THREAD

**Issue by m-sundman** [mintsoft/kodi.plugin.ytchannels#46] opened 2024-02-26 22:27 UTC
Selecting "add channel to root" and then either by name or trying to search for something results in an error message telling me to check the logs. Here's some log:
```
2024-02-27 00:20:30.661 T:1668    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'urllib.error.HTTPError'>
                                                   Error Contents: HTTP Error 400: Bad Request
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.ytchannels/default.py", line 4, in <module>
                                                       ytchannels_main()
                                                     File "/storage/.kodi/addons/plugin.video.ytchannels/resources/lib/ytchannels.py", line 382, in ytchannels_main
                                                       help_list=search_channel_by_username(channel_name)
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.ytchannels/resources/lib/functions.py", line 363, in search_channel_by_username
                                                       read = read_url(req_url)
                                                              ^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.ytchannels/resources/lib/functions.py", line 188, in read_url
                                                       response = urllib.request.urlopen(req)
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/usr/lib/python3.11/urllib/request.py", line 216, in urlopen
                                                     File "/usr/lib/python3.11/urllib/request.py", line 525, in open
                                                     File "/usr/lib/python3.11/urllib/request.py", line 634, in http_response
                                                     File "/usr/lib/python3.11/urllib/request.py", line 563, in error
                                                     File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
                                                     File "/usr/lib/python3.11/urllib/request.py", line 643, in http_error_default
                                                   urllib.error.HTTPError: HTTP Error 400: Bad Request
                                                   -->End of Python script error report<--
```

**Comment by m-sundman** [comment] 2024-02-26 22:42
And searching:
```
2024-02-27 00:20:09.681 T:1655    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'urllib.error.HTTPError'>
                                                   Error Contents: HTTP Error 400: Bad Request
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.ytchannels/default.py", line 4, in <module>
                                                       ytchannels_main()
                                                     File "/storage/.kodi/addons/plugin.video.ytchannels/resources/lib/ytchannels.py", line 358, in ytchannels_main
                                                       results=search_channel(channel_name)
                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.ytchannels/resources/lib/functions.py", line 338, in search_channel
                                                       read = read_url(req_url)
                                                              ^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.ytchannels/resources/lib/functions.py", line 188, in read_url
                                                       response = urllib.request.urlopen(req)
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/usr/lib/python3.11/urllib/request.py", line 216, in urlopen
                                                     File "/usr/lib/python3.11/urllib/request.py", line 525, in open
                                                     File "/usr/lib/python3.11/urllib/request.py", line 634, in http_response
                                                     File "/usr/lib/python3.11/urllib/request.py", line 563, in error
                                                     File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
                                                     File "/usr/lib/python3.11/urllib/request.py", line 643, in http_error_default
                                                   urllib.error.HTTPError: HTTP Error 400: Bad Request
                                                   -->End of Python script error report<--
```

**Comment by m-sundman** [comment] 2024-02-26 23:11
Manually opening https://www.googleapis.com/youtube/v3/search?q=mysearchterm&type=channel&part=snippet&maxResults=5&key=MyApiKey in my browser works just fine.

**Comment by mintsoft** [comment] 2024-02-28 08:44
Hmm! That's interesting, I've just rechecked on a few installs here and it's not a problem that I'm experiencing.

Do you have any VPNs or proxies etc that could be getting in the way?
What version of KODI and ytchannels do you have on?
What OS is this running under?

**Comment by m-sundman** [comment] 2024-03-04 17:40
> Do you have any VPNs or proxies etc that could be getting in the way?

Nope.

> What version of KODI and ytchannels do you have on?

Newest up-to-date.

> What OS is this running under?

CoreELEC

> Have you configured the YouTube API key in the addon settings? It should have asked you to do that when you opened it for the first time

Yes. And when it just caused this problem I also tried adding the API key (and client ID and secret) in the file according to the link that the installation instructions told to follow.

**Comment by mintsoft** [comment] 2024-03-04 18:28
Hmm! Very interesting. Does the normal Youtube addon work with the same API key?

**Comment by mintsoft** [comment] 2024-03-13 11:58
I'm going to close this for now because I cannot reproduce this at all; if anyone else experiences this issue I'll happily take another look or add more debugging info, but I'm at a loss at the moment.

**Closed by mintsoft** 2024-03-13 11:58 UTC
Labels: investigating
